cashu.md
bitcointxoko/guides pull request #6
Opened 2024-10-23 19:38 UTC by aandia

Euskarako atala

2024-10-24 11:22 UTC, ra5pvt1n commented on eu/cashu.md
> +Cashu Bitcoinentzako Ecash protokolo irekia da, transakzio azkarrak eta doakoak eskaintzen dituena. Protokolo honen ezaugarri nabarmenetako bat pribatutasun ia perfektua eskaintzea da. Nostr [nostr:n
Este no es un enlace markdown normal, así que puedes escribirlo así `nostr:npub12rv5lskctqxxs2c8rf2zlzc7xx3qpvzs3w4etgemauy9thegr43sf485vg`. Para probar una vista previa puedes ir a Habla.news y escribir un borrador pegando este texto

2024-10-24 11:23 UTC, ra5pvt1n commented on eu/cashu.md
> +Hona hemen Cashu eta on-chain Bitcoin alderatzen dituen taula, Bangkok 2023ko Bitcoin Konferentzian nostr [nostr:npub1cj6ndx5akfazux7f0vjl4fyx9k0ulf682p437fe03a9ndwqjm0tqj886t6](nostr:npub1cj6ndx5akf
Aquí también, aunque no sé si `-k` se mostrará correctamente.

2024-10-24 11:30 UTC, ra5pvt1n commented on eu/enuts.md
> +### Segurtasun kopiak
Ahora también hay una opción de copia de seguridad de semillas, pero aún no he actualizado las guías. Lo añadiré a las versiones en inglés y español más tarde hoy.

2024-10-24 11:34 UTC, ra5pvt1n commented on eu/lnurlp.md
> +Nola egin jakiteko, ikus ezazu nostr helbidea: `naddr1qvzqqqr4gupzqkvlvlma7a55ccp6d5rrdc27h3ssmdmael286mjaq5uxmqslk04fqqxnzd3exuerqdfkxccnyv3cs0uvul`.
Ya que ahora tenemos tu traducción de la guía lndhub, podemos cambiar esta línea para hacer referencia a la guía correcta así

Nola egin jakiteko, ikus ezazu nostr:naddr1qqxnzdej8y6ryvejxc6nvwpnqyg8wumn8ghj7mn0wd68ytnhd9hx2q3qtx0k0a7lw62vvqax6p3ku90tccgdka7ul4radews2wrdsg0m865sxpqqqp65w4hhl8s.

2024-10-24 11:40 UTC, ra5pvt1n requested changes
Mila esker!! He añadido algunos comentarios sobre algunas pequeñas cosas, la mayoría relacionadas con los enlaces nostr:. Una vez solucionados, podremos fusionarlos. Voy a actualizar lo de las copias de seguridad de semillas más tarde hoy y te mandaré un mensaje.

2024-10-24 11:57 UTC, ra5pvt1n commented on eu/cashu.md
> +Hona hemen Cashu eta on-chain Bitcoin alderatzen dituen taula, Bangkok 2023ko Bitcoin Konferentzian nostr [nostr:npub1cj6ndx5akfazux7f0vjl4fyx9k0ulf682p437fe03a9ndwqjm0tqj886t6](nostr:npub1cj6ndx5akf
Parece que sí que se renderiza correctamente!

<img width="749" alt="Screenshot 2024-10-24 at 13 56 02" src="https://github.com/user-attachments/assets/cb16865b-7e9b-4cd0-a898-aadad3eda53c">


<img width="111" alt="Screenshot 2024-10-24 at 13 56 09" src="https://github.com/user-attachments/assets/a63a76bf-32f0-4842-9bed-ecb485cbb094">

2024-10-25 11:22 UTC, aandia commented on eu/cashu.md
> +Hona hemen Cashu eta on-chain Bitcoin alderatzen dituen taula, Bangkok 2023ko Bitcoin Konferentzian nostr [nostr:npub1cj6ndx5akfazux7f0vjl4fyx9k0ulf682p437fe03a9ndwqjm0tqj886t6](nostr:npub1cj6ndx5akf
Perfecto. Gracias!

2024-10-25 17:54 UTC, aandia commented
Perfecto !

2024-10-25 18:22 UTC, closed without merging

2024-10-25 19:55 UTC, aandia reviewed
aldatuta